### ISSUE TITLE
Add alphabetic sorting of schema members and all vectors 

### ISSUE THREAD

**Issue by mgrbyte** [Yuppiechef/datomic-schema#21]
Would it possible to add this? It'd be super useful for easing schema diffs.

**Comment by CmdrDats** [comment]
I'm not entirely sure what you mean with this? Do you mean the output schema? do you have an example of what you want it to do?

**Comment by mgrbyte** [comment]
Yes, sorry - within the output schema is correct.

The workflow the project I work on currently follows a pattern where a new database schema is generated periodically.  There are minor differences between the schema for the database at each iteration, e.g: [A](/WormBase/pseudoace/blob/develop/generated-schemas/schema256.edn) and [B](/WormBase/pseudoace/blob/develop/generated-schemas/schema256.edn)

In order to easily see the difference between two such schema, it would be great if it was (optionally perhaps?) possible to have the members of the schema ordered, e.g:

```clojure
(schema
 position-matrix
 (fields
  [background :ref :component]
  [values :ref :many :component]
  [id :string :unique-identity]
  [description :ref :many :component]
  [brief-id :string :indexed]
  [type :enum [:weight :frequency]]
  [threshold :double :many]
  [consensus :ref :many :component]
  [sites-used :long]
  [derived-from-matrix :ref :many]
  [bound-by-gene-product :ref :many :component]
  [transcription-factor :ref :many :component]
  [remark :ref :many :component]))
```

becomes:

```clojure

(schema
 position-matrix
 (fields
  [background :ref :component]
  [bound-by-gene-product :ref :many :component]
  [brief-id :string :indexed]
  [consensus :ref :many :component]
  [derived-from-matrix :ref :many]
  [description :ref :many :component]
  [id :string :unique-identity]
  [remark :ref :many :component])
  [sites-used :long]
  [threshold :double :many]
  [transcription-factor :ref :many :component]
  [type :enum [:weight :frequency]]
  [values :ref :many :component] )
```
(and additionally within all `enum` `[:a :b :c]` constructs)

**Comment by CmdrDats** [comment]
Thanks for clarifying :)

Hmm, interesting usecase - I wouldn't have thought this a good fit for dumping generated schema. I would have rather simply dumped the existing datomic schema datastructures directly..

However, this does look like an issue in your own generation code:

https://github.com/WormBase/pseudoace/blob/develop/src/pseudoace/schema_datomic.clj#L84

you can simply sort alphabetically here? Of course, datomic-schema could insert the schema alphabetically to start with, but added fields won't be able to maintain this invariant, given that you're sorting by id - so fields added later will always get added on the end.

Another alternative that I would also suggest is that you should programmatically compare data structures (even something like clojure's diff function should suffice) and build a quick report on the parts that have changes, instead of trying to eyeball the subtle differences?

To be honest, if the order of inserting the schema into the db mattered, I think the correct way would be to insert them in the same order that they are defined in the `(fields ...)` form. Even then though, because of being able to arbitrarily insert a form inbetween, this is not a good fit for trying to maintain that invariant. So the best would be to leave as 'random insert' (basically hashmap ordered) just so there's less assumptions about it in client code.

**Comment by mgrbyte** [comment]
@CmdrDats Thank you very much for looking at this!
I've misinterpreted where the schema gets outputted as you've eluded to, this is something that should be fixed in pseudoace, not in datomic-schema. sorry for the noise!
Doing a report using `diff` would be even better :+1: 
Thanks again! (and sorry for the noise)

**Comment by CmdrDats** [comment]
No worries at all - only glad to have been able to help :) Also nice to see datomic-schema used in the wild!

Wishing you all the best! 👍
